name: leafbidapi
services:
  api:
    image: api
    container_name: leafbidapi-api
    volumes:
      - ./dpkeys:/app/dpkeys
      - ./wwwroot/uploads:/app/wwwroot/uploads
    ports:
      - "5001:8080"
    environment:
      - SQL_PORT=1433
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=LeafBidDb;User Id=sa;Password=ibUu6nv7tuwt66MJ9cVdkXJJdN;TrustServerCertificate=True;
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - leafbidapi-network
    depends_on:
      - mssql

  mssql:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: leafbidapi-mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "ibUu6nv7tuwt66MJ9cVdkXJJdN"
    ports:
      - "1430:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - leafbidapi-network

volumes:
  mssql_data:

networks:
  leafbidapi-network:
    driver: bridge
